import torch


class Config:
    """
    Configuration for RelFuse-Net, matching the manuscript specification.

    Data source: MIMIC-CXR-JPG + MIMIC-IV (NOT MIMIC-III).
    MIMIC-CXR shares its subject_id/hadm_id namespace with MIMIC-IV, not MIMIC-III,
    so MIMIC-IV is the only PhysioNet source that can be joined to MIMIC-CXR by ID.
    Required MIMIC-IV tables (hosp module): patients, admissions, diagnoses_icd,
    hcpcsevents (procedure/CPT-style codes), labevents (or a curated lab/vital subset).
    """

    # --- System Settings ---
    DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'
    SEED = 42
    NUM_WORKERS = 4
    NUM_RUNS = 5  # independent runs for mean +/- std reporting (Table 7/8)

    # --- Evaluation scenario (Table 2 / Ablation Study: prospective vs retrospective) ---
    # "A" = prospective / report-free: the radiology report is NEVER shown to the text
    #       encoder (RelFuseNet.forward zeroes h_text instead of encoding real report
    #       content), matching the only leakage-safe predictor per the t0 table.
    # "B" = retrospective / report-assisted (the full model): the report is encoded
    #       normally. Scenario B must never be reported as a prospective predictor.
    SCENARIO = "B"
    SCENARIOS_FOR_ABLATION = ["A", "B"]  # used by train.py's ablation entry point

    # --- Raw source paths ---
    # For local smoke-testing (no real PhysioNet data yet): point at the seed
    # data generated by preprocessing/generate_physionet_seed.py.
    #
    # Once your PhysioNet account can actually download data (see
    # preprocessing/download_mimic_subset.py), switch this single prefix from
    # "./data/mimic_seed" to "./data/mimic_subset" -- nothing else below needs
    # to change, the two scripts write an identical directory layout.
    _MIMIC_ROOT = "./data/mimic_subset"        # real PhysioNet MIMIC-CXR-JPG + MIMIC-IV data (was ./data/mimic_seed synthetic)
    _CXR_JPG_VERSION = "2.1.0"
    _MIMIC_IV_VERSION = "3.1"

    MIMIC_CXR_JPG_DIR = f"{_MIMIC_ROOT}/mimic-cxr-jpg/{_CXR_JPG_VERSION}"
    MIMIC_CXR_METADATA_CSV = f"{MIMIC_CXR_JPG_DIR}/mimic-cxr-2.0.0-metadata.csv"
    MIMIC_CXR_CHEXPERT_CSV = f"{MIMIC_CXR_JPG_DIR}/mimic-cxr-2.0.0-chexpert.csv"
    MIMIC_CXR_SPLIT_CSV = f"{MIMIC_CXR_JPG_DIR}/mimic-cxr-2.0.0-split.csv"
    MIMIC_CXR_REPORTS_DIR = f"{_MIMIC_ROOT}/reports/files"  # download_mimic_subset.py extracts reports here (separate tree from the JPG dir)
    MIMIC_IV_HOSP_DIR = f"{_MIMIC_ROOT}/mimiciv/{_MIMIC_IV_VERSION}/hosp"

    # --- Processed / pipeline output paths ---
    DATA_DIR = "./data"
    PROCESSED_DIR = "./data/processed"
    CSV_TRAIN = "./data/processed/mimic_train.csv"
    CSV_VAL = "./data/processed/mimic_val.csv"
    CSV_TEST = "./data/processed/mimic_test.csv"
    GRAPH_EDGES_TRAIN = "./data/processed/train_graph_edges.pt"
    # IMG_DIR must be the CXR project's "files" root: build_mimic_dataset.py writes
    # image_path values relative to it (e.g. "p10/p10000032/s5.../<dicom>.jpg"),
    # matching MIMIC-CXR-JPG's own on-disk layout under <root>/files/.
    IMG_DIR = f"{MIMIC_CXR_JPG_DIR}/files"

    # --- Cohort eligibility (Section 4.1.1) ---
    LAB_WINDOW_HOURS = 48  # tabular EHR must fall within this window before X-ray time t0
    VIEW_PRIORITY = ["PA", "AP", "LATERAL", "LL"]  # representative-view selection order

    # --- Split (patient-level, Section 4.1.1) ---
    TRAIN_RATIO = 0.70
    VAL_RATIO = 0.10
    TEST_RATIO = 0.20

    # --- Data Dimensions ---
    IMG_SIZE = 224          # Input resolution for DenseNet-121
    MAX_LEN = 512           # Max sequence length for Medical-Llama3 reports
    TABULAR_DIM = 50        # Number of clinical features (Lab tests, Vitals) -- D in Eq.3
    NUM_CLASSES = 14        # CheXpert label definitions

    # --- Model Architecture ---
    PROJ_DIM = 1024         # per-modality projection dim d_model (Table 3), used for
                             # image/text/tabular projections and the disentangle subspaces
    GRAPH_HIDDEN = 512      # GraphSAGE hidden units (Table 6)
    GRAPH_LAYERS = 2        # Number of GraphSAGE hops (K=2)

    # --- MLTM Settings (Section 3.2.2 / Eq. 3-4) ---
    MASK_RATIO = 0.75       # artificial masking ratio rho, applied only to OBSERVED entries
    MLTM_HIDDEN = 512
    MLTM_PRETRAIN_EPOCHS = 30   # Stage 1: self-supervised reconstruction pretraining
    MLTM_PRETRAIN_LR = 1e-3

    # --- Graph Construction (Section 3.1.2) ---
    CPT_OVERLAP_THRESHOLD = 5   # r: minimum shared CPT/HCPCS codes for a CPT-based edge
    # An ICD-based edge requires >=1 shared *historical* ICD code (admissions that
    # discharged strictly before the current admission's admittime).

    # --- Disentanglement / vCLUB (Eq. 7-9) ---
    VCLUB_HIDDEN = 256
    DISENTANGLE_BETA = 0.1   # beta weight on L_Disentangle in L_total (Eq. 9)

    # --- Optimization (Table 6) ---
    BATCH_SIZE = 32
    EPOCHS = 50
    LR = 2e-4
    WEIGHT_DECAY = 1e-2
    LR_MIN = 1e-6            # cosine-annealing floor

    # --- LLM Settings (Medical-Llama3) ---
    # Set to True to load the 8B model (requires a GPU with enough VRAM for 4-bit + LoRA).
    # Set to False to use a lightweight proxy (DistilBERT) for debugging/smoke tests only;
    # NEVER report results produced with USE_REAL_LLM=False as the paper's findings.
    USE_REAL_LLM = True
    LLM_ID = "meta-llama/Meta-Llama-3-8B"
    LORA_R = 16
    LORA_ALPHA = 32
    LORA_DROPOUT = 0.1
